##################################
# Monolith pod with all services #
##################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-demo-deploy
  labels:
    app: monolith-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith-demo
  template:
    metadata:
      labels:
        app: monolith-demo
    spec:
      containers:
      - name: monolith-demo
        image: moleculer/demo
        env: 
        - name: SERVICEDIR
          value: services
        - name: SERVICES
          value: "*.service.js"
        ports:
        - containerPort: 3000

---
#################################
# K8S Service for API Gateway   #
#################################
apiVersion: v1
kind: Service
metadata:
  name: monolith-demo-api-gateway
spec:
  selector:
    app: monolith-demo
    
  ports:
    - name: http
      port: 3000
      nodePort: 30000
      
  type: NodePort 